import type { Metadata } from "next";
import { NavigationMenu } from "@/components/ui/navigation-menu";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <div>
          <Sidebar></Sidebar>
        </div>
        {children}
      </body>
    </html>
  );
}
