import type { Metadata } from 'next';
import { NavigationMenu } from '@/components/ui/navigation-menu';
import './globals.css';
import { Sidebar } from '@/components/sidebar';
import { Poppins } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // escolha os pesos que você precisa
  variable: '--font-poppins',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={poppins.variable}>
      <body className={`antialiased`}>
        <div>
          <Sidebar></Sidebar>
        </div>
        {children}
      </body>
    </html>
  );
}
